/**
 * IndexedDB-backed FIFO queue for fetch requests that fail while offline.
 *
 * Use case: student is on the learn page, drafts an error card, taps 분석
 * while disconnected. Instead of dropping the request we serialize it into
 * IDB and replay it when the browser fires `online`.
 *
 * The queue stores the URL, method, headers, and (text) body. We do NOT
 * persist FormData or streams — those would round-trip poorly through IDB
 * and the analyze/submit endpoints both accept JSON. A request becomes
 * "stuck" if it 4xxs on replay; the API contract for those endpoints is
 * idempotent on session_id, so retrying a 5xx is safe.
 *
 * Public API:
 *   - enqueueOfflineRequest({ url, method, headers, body, kind, label })
 *   - flushOfflineQueue() → { successes, failures }
 *   - subscribeOfflineQueue(cb) → unsubscribe
 *   - getOfflineQueueLength()
 *
 * The provider component in components/OfflineQueueFlusher.tsx wires the
 * `online` event to flushOfflineQueue and renders a toast.
 */

const DB_NAME = 'wunote-offline'
const DB_VERSION = 1
const STORE = 'queue'

export type OfflineKind = 'analyze' | 'submit' | 'other'

export interface OfflineRequestRecord {
  /** auto-generated by IDB autoIncrement */
  id?: number
  url: string
  method: string
  headers: Record<string, string>
  /** JSON-stringified body. We assume application/json. */
  body: string
  kind: OfflineKind
  /** human-readable identifier for the toast (e.g., "오류카드 — 1장 5과") */
  label?: string
  createdAt: number
  /** number of replay attempts so far */
  attempts: number
}

interface IDBLike {
  open(name: string, version: number): IDBOpenDBRequest
}

function getIDB(): IDBLike | null {
  if (typeof indexedDB === 'undefined') return null
  return indexedDB
}

function openDB(): Promise<IDBDatabase> {
  return new Promise((resolve, reject) => {
    const idb = getIDB()
    if (!idb) {
      reject(new Error('IndexedDB unavailable in this environment'))
      return
    }
    const req = idb.open(DB_NAME, DB_VERSION)
    req.onupgradeneeded = () => {
      const db = req.result
      if (!db.objectStoreNames.contains(STORE)) {
        db.createObjectStore(STORE, { keyPath: 'id', autoIncrement: true })
      }
    }
    req.onsuccess = () => resolve(req.result)
    req.onerror = () => reject(req.error ?? new Error('failed to open IDB'))
  })
}

function txStore(db: IDBDatabase, mode: IDBTransactionMode): IDBObjectStore {
  return db.transaction(STORE, mode).objectStore(STORE)
}

type Listener = (count: number) => void
const listeners = new Set<Listener>()

async function notify(): Promise<void> {
  const count = await getOfflineQueueLength().catch(() => 0)
  for (const l of listeners) {
    try {
      l(count)
    } catch {
      // ignore subscriber errors
    }
  }
}

export function subscribeOfflineQueue(cb: Listener): () => void {
  listeners.add(cb)
  // fire once with current count
  getOfflineQueueLength().then(cb).catch(() => cb(0))
  return () => {
    listeners.delete(cb)
  }
}

export async function getOfflineQueueLength(): Promise<number> {
  if (!getIDB()) return 0
  const db = await openDB()
  return new Promise<number>((resolve, reject) => {
    const req = txStore(db, 'readonly').count()
    req.onsuccess = () => {
      db.close()
      resolve(req.result)
    }
    req.onerror = () => {
      db.close()
      reject(req.error)
    }
  })
}

export async function enqueueOfflineRequest(
  rec: Omit<OfflineRequestRecord, 'id' | 'createdAt' | 'attempts'>
): Promise<number> {
  const db = await openDB()
  return new Promise<number>((resolve, reject) => {
    const full: OfflineRequestRecord = {
      ...rec,
      createdAt: Date.now(),
      attempts: 0,
    }
    const req = txStore(db, 'readwrite').add(full)
    req.onsuccess = () => {
      db.close()
      resolve(req.result as number)
      void notify()
      void registerBackgroundSync()
    }
    req.onerror = () => {
      db.close()
      reject(req.error)
    }
  })
}

async function listAll(db: IDBDatabase): Promise<OfflineRequestRecord[]> {
  return new Promise<OfflineRequestRecord[]>((resolve, reject) => {
    const req = txStore(db, 'readonly').getAll()
    req.onsuccess = () => resolve(req.result as OfflineRequestRecord[])
    req.onerror = () => reject(req.error)
  })
}

async function remove(db: IDBDatabase, id: number): Promise<void> {
  return new Promise<void>((resolve, reject) => {
    const req = txStore(db, 'readwrite').delete(id)
    req.onsuccess = () => resolve()
    req.onerror = () => reject(req.error)
  })
}

async function update(db: IDBDatabase, rec: OfflineRequestRecord): Promise<void> {
  return new Promise<void>((resolve, reject) => {
    const req = txStore(db, 'readwrite').put(rec)
    req.onsuccess = () => resolve()
    req.onerror = () => reject(req.error)
  })
}

export interface FlushResult {
  successes: number
  failures: number
  /** records that exhausted retries and were dropped */
  dropped: number
}

const MAX_ATTEMPTS = 5

/**
 * Replay every queued request in FIFO order. Stops early on the first
 * network error — if we're still effectively offline, no point hammering.
 *
 * - 2xx response → drop record from queue
 * - 4xx response (other than 408/429) → drop record (it'll never succeed)
 * - 408/429/5xx → keep, increment attempts
 * - thrown (network) → keep, increment attempts, abort flush
 *
 * Records that hit MAX_ATTEMPTS are dropped to prevent unbounded growth.
 */
export async function flushOfflineQueue(): Promise<FlushResult> {
  if (!getIDB()) return { successes: 0, failures: 0, dropped: 0 }
  if (typeof navigator !== 'undefined' && navigator.onLine === false) {
    return { successes: 0, failures: 0, dropped: 0 }
  }

  const db = await openDB()
  let records: OfflineRequestRecord[]
  try {
    records = await listAll(db)
  } catch (err) {
    db.close()
    throw err
  }

  // FIFO: oldest first.
  records.sort((a, b) => a.createdAt - b.createdAt)

  let successes = 0
  let failures = 0
  let dropped = 0

  for (const rec of records) {
    try {
      const res = await fetch(rec.url, {
        method: rec.method,
        headers: rec.headers,
        body: rec.method === 'GET' || rec.method === 'HEAD' ? undefined : rec.body,
        credentials: 'include',
      })
      if (res.ok) {
        if (rec.id !== undefined) await remove(db, rec.id)
        successes += 1
        continue
      }
      // Permanent client errors → drop (no point in retrying a 400).
      if (res.status >= 400 && res.status < 500 && res.status !== 408 && res.status !== 429) {
        if (rec.id !== undefined) await remove(db, rec.id)
        dropped += 1
        continue
      }
      // Transient (5xx, 408, 429) → bump attempts, drop if exhausted.
      const next = { ...rec, attempts: rec.attempts + 1 }
      if (next.attempts >= MAX_ATTEMPTS) {
        if (rec.id !== undefined) await remove(db, rec.id)
        dropped += 1
      } else {
        await update(db, next)
        failures += 1
      }
    } catch {
      // Network error — bump and stop flushing; assume we lost connectivity again.
      const next = { ...rec, attempts: rec.attempts + 1 }
      if (next.attempts >= MAX_ATTEMPTS) {
        if (rec.id !== undefined) await remove(db, rec.id)
        dropped += 1
      } else {
        await update(db, next).catch(() => {})
        failures += 1
      }
      break
    }
  }

  db.close()
  void notify()
  return { successes, failures, dropped }
}

/**
 * Convenience: try the request, queue it on network error, return either
 * the real Response or a synthetic { ok: false, queued: true } sentinel.
 *
 * Caller is responsible for showing UI for the queued state (the toast in
 * OfflineQueueFlusher is global, but call sites typically also need to
 * stop their own loading spinner and reset their "submitted" state).
 */
export interface QueuedFetchOptions {
  kind: OfflineKind
  label?: string
}

export interface QueuedFetchSentinel {
  ok: false
  queued: true
  status: 0
}

export async function fetchOrEnqueue(
  url: string,
  init: RequestInit,
  opts: QueuedFetchOptions
): Promise<Response | QueuedFetchSentinel> {
  // Always try the network first, even if navigator says offline — some
  // captive-portal / VPN setups misreport. Network throwing is the truth.
  try {
    return await fetch(url, init)
  } catch {
    const headers: Record<string, string> = {}
    const initHeaders = init.headers
    if (initHeaders instanceof Headers) {
      initHeaders.forEach((v, k) => {
        headers[k] = v
      })
    } else if (Array.isArray(initHeaders)) {
      for (const [k, v] of initHeaders) headers[k] = v
    } else if (initHeaders && typeof initHeaders === 'object') {
      Object.assign(headers, initHeaders as Record<string, string>)
    }

    const body = typeof init.body === 'string' ? init.body : ''
    if (typeof init.body !== 'string' && init.body != null) {
      // We only support stringified JSON bodies for queueing.
      throw new Error('fetchOrEnqueue: only string bodies are queueable')
    }

    await enqueueOfflineRequest({
      url,
      method: (init.method ?? 'GET').toUpperCase(),
      headers,
      body,
      kind: opts.kind,
      label: opts.label,
    })

    return { ok: false, queued: true, status: 0 }
  }
}

export function isQueuedSentinel(x: unknown): x is QueuedFetchSentinel {
  return (
    typeof x === 'object' &&
    x !== null &&
    (x as { queued?: unknown }).queued === true &&
    (x as { status?: unknown }).status === 0
  )
}

/**
 * Best-effort registration with the SW Background Sync API. Returns silently
 * on browsers that don't implement it (notably iOS Safari) — the client-side
 * `online` listener handles flushing in that case.
 */
async function registerBackgroundSync(): Promise<void> {
  if (typeof navigator === 'undefined' || !('serviceWorker' in navigator)) return
  try {
    const reg = await navigator.serviceWorker.ready
    const sync = (reg as unknown as { sync?: { register: (tag: string) => Promise<void> } }).sync
    if (sync?.register) {
      await sync.register('wunote-offline-flush')
    }
  } catch {
    // Background Sync unavailable — no-op.
  }
}

/** Test seam — wipes the entire queue. Don't call from production code. */
export async function _clearOfflineQueue(): Promise<void> {
  if (!getIDB()) return
  const db = await openDB()
  return new Promise<void>((resolve, reject) => {
    const req = txStore(db, 'readwrite').clear()
    req.onsuccess = () => {
      db.close()
      resolve()
      void notify()
    }
    req.onerror = () => {
      db.close()
      reject(req.error)
    }
  })
}
