import { NextResponse } from 'next/server'

const SPEC = {
  openapi: '3.0.3',
  info: {
    title: 'Wunote.ai LMS API',
    description:
      'REST API for Canvas/Moodle LMS integration with Wunote.ai. ' +
      'All `/api/lms/*` endpoints require `Authorization: Bearer <api-key>`. ' +
      'API keys are generated by professors at `/settings/api-keys`.',
    version: '1.0.0',
    contact: { email: 'support@wunote.ai' },
  },
  servers: [{ url: '', description: 'Current host' }],
  security: [{ bearerAuth: [] }],
  components: {
    securitySchemes: {
      bearerAuth: {
        type: 'http',
        scheme: 'bearer',
        bearerFormat: 'hex64',
        description: 'API key generated by the professor in the Wunote.ai settings page.',
      },
    },
    schemas: {
      Error: {
        type: 'object',
        properties: { error: { type: 'string' } },
        required: ['error'],
      },
      LMSClass: {
        type: 'object',
        properties: {
          id: { type: 'string', format: 'uuid' },
          name: { type: 'string' },
          semester: { type: 'string', example: '2026-1' },
          invite_code: { type: 'string' },
          is_active: { type: 'boolean' },
          student_count: { type: 'integer' },
          created_at: { type: 'string', format: 'date-time' },
        },
        required: ['id', 'name', 'semester', 'invite_code', 'is_active', 'student_count', 'created_at'],
      },
      LMSStudent: {
        type: 'object',
        properties: {
          id: { type: 'string', format: 'uuid', description: 'Supabase auth user ID' },
          name: { type: 'string', nullable: true },
          student_id: { type: 'string', nullable: true, description: 'University student number' },
          email: { type: 'string', format: 'email', nullable: true },
          enrolled_at: { type: 'string', format: 'date-time' },
        },
        required: ['id', 'enrolled_at'],
      },
      LMSAssignment: {
        type: 'object',
        properties: {
          id: { type: 'string', format: 'uuid' },
          title: { type: 'string' },
          prompt_text: { type: 'string' },
          due_date: { type: 'string', format: 'date-time', nullable: true },
          created_at: { type: 'string', format: 'date-time' },
        },
        required: ['id', 'title', 'prompt_text', 'created_at'],
      },
      LMSGradeEntry: {
        type: 'object',
        properties: {
          student_id: { type: 'string', format: 'uuid' },
          student_name: { type: 'string', nullable: true },
          student_number: { type: 'string', nullable: true },
          assignment_id: { type: 'string', format: 'uuid' },
          assignment_title: { type: 'string' },
          session_id: { type: 'string', format: 'uuid', nullable: true },
          draft_error_count: { type: 'integer', nullable: true },
          revision_error_count: { type: 'integer', nullable: true },
          improvement: {
            type: 'integer',
            nullable: true,
            description: 'draft_error_count − revision_error_count; positive = improvement',
          },
          submitted_at: { type: 'string', format: 'date-time', nullable: true },
        },
        required: ['student_id', 'assignment_id'],
      },
      LMSApiKeyRecord: {
        type: 'object',
        properties: {
          id: { type: 'string', format: 'uuid' },
          name: { type: 'string' },
          key_prefix: { type: 'string', description: 'First 8 chars of hash + "…" (never the raw key)' },
          scopes: { type: 'array', items: { type: 'string' } },
          last_used_at: { type: 'string', format: 'date-time', nullable: true },
          created_at: { type: 'string', format: 'date-time' },
          is_active: { type: 'boolean' },
        },
        required: ['id', 'name', 'key_prefix', 'scopes', 'created_at', 'is_active'],
      },
    },
    parameters: {
      classId: {
        name: 'classId',
        in: 'path',
        required: true,
        schema: { type: 'string', format: 'uuid' },
        description: 'Class UUID',
      },
    },
    responses: {
      Unauthorized: {
        description: 'Missing or invalid API key, or rate limit exceeded (100 req/min)',
        content: { 'application/json': { schema: { $ref: '#/components/schemas/Error' } } },
      },
      NotFound: {
        description: 'Resource not found or not owned by this professor',
        content: { 'application/json': { schema: { $ref: '#/components/schemas/Error' } } },
      },
    },
  },
  paths: {
    '/api/lms/classes': {
      get: {
        summary: "List professor's classes",
        description: 'Returns all classes owned by the professor associated with the API key.',
        operationId: 'listClasses',
        tags: ['Classes'],
        responses: {
          '200': {
            description: 'OK',
            content: {
              'application/json': {
                schema: {
                  type: 'object',
                  properties: {
                    classes: { type: 'array', items: { $ref: '#/components/schemas/LMSClass' } },
                  },
                },
              },
            },
          },
          '401': { $ref: '#/components/responses/Unauthorized' },
        },
      },
    },
    '/api/lms/classes/{classId}/students': {
      get: {
        summary: 'Get class roster',
        operationId: 'listStudents',
        tags: ['Classes'],
        parameters: [{ $ref: '#/components/parameters/classId' }],
        responses: {
          '200': {
            description: 'OK',
            content: {
              'application/json': {
                schema: {
                  type: 'object',
                  properties: {
                    students: { type: 'array', items: { $ref: '#/components/schemas/LMSStudent' } },
                  },
                },
              },
            },
          },
          '401': { $ref: '#/components/responses/Unauthorized' },
          '404': { $ref: '#/components/responses/NotFound' },
        },
      },
    },
    '/api/lms/classes/{classId}/assignments': {
      get: {
        summary: 'List assignments for a class',
        operationId: 'listAssignments',
        tags: ['Classes'],
        parameters: [{ $ref: '#/components/parameters/classId' }],
        responses: {
          '200': {
            description: 'OK',
            content: {
              'application/json': {
                schema: {
                  type: 'object',
                  properties: {
                    assignments: { type: 'array', items: { $ref: '#/components/schemas/LMSAssignment' } },
                  },
                },
              },
            },
          },
          '401': { $ref: '#/components/responses/Unauthorized' },
          '404': { $ref: '#/components/responses/NotFound' },
        },
      },
    },
    '/api/lms/classes/{classId}/grades': {
      get: {
        summary: 'Export grades for a class',
        description:
          'Returns per-student, per-assignment error counts and improvement scores. ' +
          'Optionally filter by `assignmentId`.',
        operationId: 'listGrades',
        tags: ['Classes'],
        parameters: [
          { $ref: '#/components/parameters/classId' },
          {
            name: 'assignmentId',
            in: 'query',
            required: false,
            schema: { type: 'string', format: 'uuid' },
            description: 'Filter to a single assignment',
          },
        ],
        responses: {
          '200': {
            description: 'OK',
            content: {
              'application/json': {
                schema: {
                  type: 'object',
                  properties: {
                    grades: { type: 'array', items: { $ref: '#/components/schemas/LMSGradeEntry' } },
                  },
                },
              },
            },
          },
          '401': { $ref: '#/components/responses/Unauthorized' },
          '404': { $ref: '#/components/responses/NotFound' },
        },
      },
    },
    '/api/lms/keys': {
      get: {
        summary: "List professor's API keys",
        description:
          'Session-authenticated (cookie). Returns metadata only — raw keys are never re-exposed.',
        operationId: 'listApiKeys',
        tags: ['API Keys'],
        security: [{ cookieAuth: [] }],
        responses: {
          '200': {
            description: 'OK',
            content: {
              'application/json': {
                schema: {
                  type: 'object',
                  properties: {
                    keys: { type: 'array', items: { $ref: '#/components/schemas/LMSApiKeyRecord' } },
                  },
                },
              },
            },
          },
          '401': { $ref: '#/components/responses/Unauthorized' },
        },
      },
      post: {
        summary: 'Create a new API key',
        description:
          'Session-authenticated. Returns the raw key **once** — store it securely. ' +
          'Subsequent calls only reveal the key prefix.',
        operationId: 'createApiKey',
        tags: ['API Keys'],
        security: [{ cookieAuth: [] }],
        requestBody: {
          required: true,
          content: {
            'application/json': {
              schema: {
                type: 'object',
                properties: {
                  name: { type: 'string', example: 'Canvas prod' },
                  scopes: {
                    type: 'array',
                    items: { type: 'string', enum: ['classes', 'students', 'assignments', 'grades'] },
                    example: ['classes', 'grades'],
                  },
                },
                required: ['name'],
              },
            },
          },
        },
        responses: {
          '201': {
            description: 'Key created',
            content: {
              'application/json': {
                schema: {
                  type: 'object',
                  properties: {
                    key: { type: 'string', description: 'Raw 64-char hex key — shown once only' },
                    record: { $ref: '#/components/schemas/LMSApiKeyRecord' },
                  },
                },
              },
            },
          },
          '400': {
            description: 'Validation error',
            content: { 'application/json': { schema: { $ref: '#/components/schemas/Error' } } },
          },
          '401': { $ref: '#/components/responses/Unauthorized' },
        },
      },
      delete: {
        summary: 'Revoke an API key',
        description: 'Session-authenticated. Marks the key inactive; it will immediately stop working.',
        operationId: 'revokeApiKey',
        tags: ['API Keys'],
        security: [{ cookieAuth: [] }],
        parameters: [
          {
            name: 'id',
            in: 'query',
            required: true,
            schema: { type: 'string', format: 'uuid' },
            description: 'API key ID to revoke',
          },
        ],
        responses: {
          '200': {
            description: 'Revoked',
            content: {
              'application/json': {
                schema: { type: 'object', properties: { success: { type: 'boolean' } } },
              },
            },
          },
          '401': { $ref: '#/components/responses/Unauthorized' },
        },
      },
    },
  },
  tags: [
    { name: 'Classes', description: 'LMS data endpoints — secured by API key' },
    { name: 'API Keys', description: 'Key management — secured by professor session cookie' },
  ],
}

export async function GET() {
  return NextResponse.json(SPEC, {
    headers: { 'Cache-Control': 'public, max-age=3600' },
  })
}
